### ISSUE TITLE
GwWork defaults to ETD administrative set

### ISSUE THREAD

**Issue by kilahimm** [gwu-libraries/scholarspace-hyrax#222] opened 2019-05-02 15:07 UTC
When uploading a GwWork via the web UI it is being assigned to the ETD admin set by default rather than the GwWork admin set.

**Comment by kerchner** [comment] 2019-05-03 12:00
Closing as duplicate of #178 which is fixed in 1.2.0

**Closed by kerchner** 2019-05-03 12:00 UTC
Labels: bug, duplicate
