### ISSUE TITLE
Default administrative set for GW Works is ETDs

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/scholarspace-hyrax#201] opened 2019-02-21 20:10 UTC
When staff use the manual uploader form to create a GW Work, the default Administrative Set is ETDs. Staff have to remember to click a new tab to update it. The error rate has been high as a result (many GW Works in the ETD administrative set).

**Comment by kerchner** [comment] 2019-02-21 20:13
Duplicate of #178

**Closed by kerchner** 2019-02-21 20:13 UTC
Labels: duplicate
